
# folder path of dataset, which includes 2 subfolders: cloudy_image/ and ground_truth/
datasets_dir: ./data/RICE_DATASET/RICE2
train_list: train_list.txt
test_list: test_list.txt
out_dir: results

cuda: True
gpu_ids: [0]

train_size: 0.80
validation_size: 0.20 # 验证集大小是占训练集的半分比
batchsize: 1
validation_batchsize: 1
epoch: 400
n_data: 100
width: 512
height: 512
threads: 0

lr: 0.0004
beta1: 0.5
lamb: 150
minimax: 1

gen_init: 
dis_init: 
in_ch: 3
out_ch: 3

manualSeed: 2
snapshot_interval: 100
